---
- name: Ubuntu 22.04 Setup
  when:
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_version == '22.04'
  block:
    - name: Removing a client
      when: operation == "remove"
      include_tasks: "ubuntu_22.04/rmclient_ubuntu_22.04.yml"
      tags:
        - rmclient
        - ir
    - name: Adding a client
      when: operation == "add"
      include_tasks: "ubuntu_22.04/addclient_ubuntu_22.04.yml"
      tags:
        - addclient
        - ir

- name: Ubuntu 20.04 Setup
  when:
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_version == '20.04'
  block:
    - name: Removing a client
      when: operation == "remove"
      include_tasks: "ubuntu_20.04/rmclient_ubuntu_20.04.yml"
      tags:
        - rmclient
        - ir
    - name: Adding a client
      when: operation == "add"
      include_tasks: "ubuntu_20.04/addclient_ubuntu_20.04.yml"
      tags:
        - addclient
        - ir

