---
- name: Setting up the rmFilter
  tags:
    - setup_rmfilter
    - setup_irside
    - ubuntu_22_04
  block:
    - name: Templating the nofilter service and timer
      template:
        src: "{{ item }}"
        dest: "/{{ item }}"
      loop:
        - "etc/systemd/system/nofilter.service"
        - "etc/systemd/system/nofilter.timer"
    
    - name: Reload systemd
      systemd:
        daemon-reload: yes
    
    - name: Enabling nofilter service and timer
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - "nofilter.service"
        - "nofilter.timer"
