---
- name: Ubuntu 22.04 Foreign side
  when:
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_version == '22.04'
  block:
    - name: Setting up OpenVPN on Foreign Server
      when: remove_ovpn|bool == false
      block:
        - name: Setting up the main server on Foreign side
          include_tasks: "ubuntu_22.04/setup_ovpn_server_ubuntu_22.04.yml"
          tags:
            - setup_foreign_server
      tags:
        - setup_foreign_side
        - ubuntu_22_04

    - name: Removing OpenVPN from Foreign Server
      when: remove_ovpn|bool == true
      block:
        - name: Removing the main server from Foreign side
          include_tasks: "ubuntu_22.04/remove_ovpn_server_ubuntu_22.04.yml"
          tags:
            - remove_foreign_server
      tags:
        - remove_foreign_side
        - ubuntu_22_04

- name: Ubuntu 20.04 Foreign side
  when:
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_version == '20.04'
  block:
    - name: Setting up OpenVPN on Foreign Server
      when: remove_ovpn|bool == false
      block:
        - name: Setting up the main server on Foreign side
          include_tasks: "ubuntu_20.04/setup_ovpn_server_ubuntu_20.04.yml"
          tags:
            - setup_foreign_server
      tags:
        - setup_foreign_side
        - ubuntu_20_04

    - name: Removing OpenVPN from Foreign Server
      when: remove_ovpn|bool == true
      block:
        - name: Removing the main server from Foreign side
          include_tasks: "ubuntu_20.04/remove_ovpn_server_ubuntu_20.04.yml"
          tags:
            - remove_foreign_server
      tags:
        - remove_foreign_side
        - ubuntu_20_04
