---
- name: Ubuntu 22.04 IR side
  when:
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_version == '22.04'
  block:
    - name: Setting up OpenVPN on IR Server
      when: remove_ovpn|bool == false
      block:
        - name: Setting up the filtering bypass routes
          include_tasks: "ubuntu_22.04/setup_rmfilter_ubuntu_22.04.yml"
          tags:
            - setup_rmfilter
      
        - name: Continuing with IR client side setup
          include_tasks: "ubuntu_22.04/setup_ovpn_client_ubuntu_22.04.yml"
          tags:
            - setup_irclient
    
        - name: Continuing with IR Server side setup
          include_tasks: "ubuntu_22.04/setup_ovpn_server_ubuntu_22.04.yml"
          tags:
            - setup_irserver
      tags:
        - setup_ir_side
        - ubuntu_22_04

    - name: Removing OpenVPN from IR Server
      when: remove_ovpn|bool == true
      block:
        - name: Removing the filtering bypass rules
          include_tasks: "ubuntu_22.04/remove_rmfilter_ubuntu_22.04.yml"
          tags:
            - remove_rmfilter
      
        - name: Removing the IR client side
          include_tasks: "ubuntu_22.04/remove_ovpn_client_ubuntu_22.04.yml"
          tags:
            - remove_irclient
    
        - name: Remvoing the IR Server side
          include_tasks: "ubuntu_22.04/remove_ovpn_server_ubuntu_22.04.yml"
          tags:
            - remove_irserver

      tags:
        - remove_ir_side
        - ubuntu_22_04
  
- name: Ubuntu 20.04 IR side
  when:
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_version == '20.04'
  block:
    - name: Setting up OpenVPN on IR Server
      when: remove_ovpn|bool == false
      block:
        - name: Setting up the filtering bypass routes
          include_tasks: "ubuntu_20.04/setup_rmfilter_ubuntu_20.04.yml"
          tags:
            - setup_rmfilter
      
        - name: Continuing with IR client side setup
          include_tasks: "ubuntu_20.04/setup_ovpn_client_ubuntu_20.04.yml"
          tags:
            - setup_irclient
    
        - name: Continuing with IR Server side setup
          include_tasks: "ubuntu_20.04/setup_ovpn_server_ubuntu_20.04.yml"
          tags:
            - setup_irserver
      tags:
        - setup_ir_side
        - ubuntu_20_04

    - name: Removing OpenVPN from IR Server
      when: remove_ovpn|bool == true
      block:
        - name: Remvoing the filtering bypass routes
          include_tasks: "ubuntu_20.04/remove_rmfilter_ubuntu_20.04.yml"
          tags:
            - remove_rmfilter
      
        - name: Removing IR client side setup
          include_tasks: "ubuntu_20.04/remove_ovpn_client_ubuntu_20.04.yml"
          tags:
            - remove_irclient
    
        - name: Removing IR Server side setup
          include_tasks: "ubuntu_20.04/remove_ovpn_server_ubuntu_20.04.yml"
          tags:
            - remove_irserver
            
      tags:
        - remove_ir_side
        - ubuntu_20_04
