# Default variables for Ubuntu systems
---
remove_ovpn: false
target_ssh_key : "keys/{{ inventory_hostname }}_ssh_key.pem"
ansible_ssh_private_key_file : "{{ target_ssh_key }}"
socks_proxy_port : "8080"
socks_proxy_duration : 600  # Keep the socks proxy online for 10 minutes, so that target have enough time to fetch the packages
openvpn_pkg_repo_host : "swupdate.openvpn.net"
iptables_path: "/usr/sbin/iptables"
ip_bin_path: "/usr/sbin/ip"
ovpn_root: "/opt/ovpn/"
secret_path: "{{ ovpn_root }}/.secret"
up_script: "{{ovpn_root}}/up_script.sh"
verbosity: 1
ovpn_FS_server_proto: "tcp-server"
ovpn_IS_client_proto: "tcp-client"
fs_server_port: 443
ic_logpath: "/var/log/openvpn-client.log"  # log path for client part on iran server
is_logpath: "/var/log/openvpn-server.log"  # log path for server part on iran server
fs_logpath: "/var/log/openvpn.log"  # log path for server part on foreign server




# Ubuntu specific settings
openvpn_ubuntu_repo_addr: "http://swupdate.openvpn.net/community/openvpn3/repos"
openvpn_ubuntu_package_name: "openvpn"
